name: repo sync

on:
  schedule:
    - cron: '*/10 * * * *'
  # Allows manual workflow run (must in default branch to work)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Sync to Upstream Repository
        uses: rovast/sync-upstream-repo@v0.0.1
        with: 
          upstream_repo: https://github.com/arrakis-test-org/arrakis-test-repo
          upstream_branch: main # change this
          downstream_branch: main # change this
          token: ${{ secrets.PAT_TOKEN }}
