name: Upstream Sync

on: 
  schedule:
    - cron: "*/10 * * * *"
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: GitHub Sync to Upstream Repository
      uses: actions/checkout@v3
      with:
      # GitHub public upstream repo
        upstream_repo: https://github.com/arrakis-test-org/arrakis-test-repo.git
